---
title: "County Research Dashboard"
author: "`r format(Sys.time())`"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    orientation: columns
    vertical_layout: fill
    editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(retrosheet)
library(shiny)
library(ggplot2)
library(grid)
library(gridExtra)
game1pbp <- read.csv("game1pbp.csv")
RedSoxGames <- getRetrosheet("play",2018,"BOS")
game1 <- RedSoxGames[[1]]
game1lineup <- data.frame(game1$start)
game1lineup <- game1lineup[,c(2,3,5)]
```

Game View {data-orientation=columns}
====================================


Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

sliderInput('playevent', 'Event', min=1, max=nrow(game1pbp),
            value=min(1, nrow(game1pbp)), step=1, round=0)

```

Outputs
-----------------------------------------------------------------------
### Base_state

```{r}



dataset1<- reactive({
  game1pbp[(input$playevent),]
})
dataset2<- reactive({
  game1pbp[(input$playevent),]
})
dataset3 <- reactive({
  game1pbp[(input$playevent),]
})

renderPlot({
  base <- (sqrt(2)/2)
  df <- data.frame(x = c(base, 0, -base, 0), y = c(0, base, 0, -base))
  dfthirdbase <- data.frame(x = c((-base+.2), (-base+.1),-base, (-base+.1)), y = c(0, .1, 0, -.1))
  dffirstbase <- data.frame(x = c((base-.2), (base-.1),base, (base-.1)), y = c(0, .1, 0, -.1))
  dfsecondbase <- data.frame(y = c((base-.2), (base-.1),base, (base-.1)), x = c(0, .1, 0, -.1))
  base_background <- ggplot(df) + geom_polygon(aes(x = x, y = y), fill = "yellowgreen")
  thirdbase <- geom_polygon(aes(x = dfthirdbase$x, y = dfthirdbase$y), fill = "black")  
  firstbase <- geom_polygon(aes(x = dffirstbase$x, y = dffirstbase$y), fill = "black")  
  secondbase <- geom_polygon(aes(x = dfsecondbase$x, y = dfsecondbase$y), fill = "black")
  if (dataset1()$firstbasebefore==1&&dataset2()$secondbasebefore==0&&dataset3()$thirdbasebefore==0){
    g <- base_background + firstbase
  }
    
  if (dataset1()$firstbasebefore==0&&dataset2()$secondbasebefore==1&&dataset3()$thirdbasebefore==0){
    g <- base_background + secondbase
  }
    
  if (dataset1()$firstbasebefore==0&&dataset2()$secondbasebefore==0&&dataset3()$thirdbasebefore==1){
    g <- base_background + thirdbase
  }
    
  if (dataset1()$firstbasebefore==1&&dataset2()$secondbasebefore==1&&dataset3()$thirdbasebefore==0){
    g <- base_background + firstbase + secondbase
  }
    
  if (dataset1()$firstbasebefore==0&&dataset2()$secondbasebefore==1&&dataset3()$thirdbasebefore==1){
    g <- base_background + thirdbase + secondbase
  }
    
  if (dataset1()$firstbasebefore==1&&dataset2()$secondbasebefore==0&&dataset3()$thirdbasebefore==1){
    g <- base_background + thirdbase + firstbase
  }
    
  if (dataset1()$firstbasebefore==1&&dataset2()$secondbasebefore==1&&dataset3()$thirdbasebefore==1){
    g <- base_background + thirdbase + firstbase + secondbase
  }
    
  if (dataset1()$firstbasebefore==0&&dataset2()$secondbasebefore==0&&dataset3()$thirdbasebefore==0){
    g <- base_background
  }
  print(g)
    
})


```

Lineups {data-orientation=Columns}
====================================

Column
-------------------------------------------------------------------------------------

## Lineup One
```{r}
grid.table(game1lineup[game1lineup$team==1,c(1,3)], rows=NULL)
```

Column
-------------------------------------------------------------------------------------

## Lineup One
```{r}
grid.table(game1lineup[game1lineup$team==0,c(1,3)], rows=NULL)

```

